Fix JSON syntax of sample_config.json
Otherwise the file could not be parsed, throwing this error:

$ node test.js

/home/pi/Documents/Code/buzzerbot9000/node_modules/configure/main.js:25
        throw new Error(msg);
              ^
Error: Unable to read or parse file "/home/pi/Documents/Code/buzzerbot9000/config.json". Exception caught: SyntaxError: Unexpected token ]
    at Object.<anonymous> (/home/pi/Documents/Code/buzzerbot9000/node_modules/configure/main.js:25:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/Documents/Code/buzzerbot9000/test.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)